version: '3'
services:
  fluentbit:
    build: ./fluent-bit
    container_name: fluentbit
    # image: fluent/fluent-bit:latest-debug
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - /var/log:/etc/host-var-log:ro
    networks:
      - esnet

  elasticsearch:
    image: elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - network.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - node.name=cluster1-node1
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - esnet

  kibana:
    image: kibana:8.14.3
    container_name: kibana
    environment:
     ELASTICSEARCH_HOSTS: http://elasticsearch:9200
     SERVER_HOSTS: 0.0.0.0
    ports:
      - "5601:5601"
    networks:
      - esnet
    depends_on:
      - elasticsearch

  memgraphmage:
    image: memgraph/memgraph-mage:latest
    container_name: memgraph-mage
    ports:
      - "7687:7687"
      - "7444:7444"
    command: ["--log-level=DEBUG"]
    networks:
      - esnet

  memgraphlab:
    image: memgraph/lab:latest
    container_name: memgraph-lab
    ports:
      - "3000:3000"
    depends_on:
      - memgraphmage
    environment:
      - QUICK_CONNECT_MG_HOST=memgraphmage
      - QUICK_CONNECT_MG_PORT=7687
    networks:
      - esnet

networks:
  esnet: