version: '3'
services:
  fluentbit:
    build: ./fluent-bit
    container_name: fluentbit
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - /var/log:/etc/host-var-log:ro
    networks:
      - esnet

  # sidecar container to run commands for setting up elasticsearch
  elasticsearch-setup:
    build: ./elasticsearch-setup
    container_name: elasticsearch-setup
    networks:
      - esnet
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - network.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - node.name=cluster1-node1
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - esnet
    healthcheck:
        test: "curl --silent --fail --user elastic:changeme localhost:9200/_cluster/health || exit 1"
        interval: 30s
        timeout: 30s
        retries: 3

  kibana:
    image: kibana:8.14.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=changeme
    # some things are just too complicated to specify as env vars... so into a yml they go
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - esnet
    depends_on:
      - elasticsearch
    healthcheck:
        test: "curl --silent --fail localhost:5601 || exit 1"
        interval: 30s
        timeout: 30s
        retries: 3

  apm-server:
    image: elastic/apm-server:8.14.3
    container_name: apm-server
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    ports:
      - 8200:8200
    command: >
       apm-server -e
         -E apm-server.host="0.0.0.0:8200"
         -E output.elasticsearch.hosts=["http://elasticsearch:9200"]
         -E output.elasticsearch.username=apm_system
         -E output.elasticsearch.password=changeme
    networks:
      - esnet
    depends_on:
      - elasticsearch
      - kibana

  memgraphmage:
    # image: memgraph/memgraph-mage:1.18.1-memgraph-2.18.1
    build: ./memgraph-mage
    container_name: memgraph-mage
    ports:
      - "7687:7687"
      - "7444:7444"
    command: ["--log-level=DEBUG"]
    networks:
      - esnet
    healthcheck:
        test: echo 'import requests; requests.get("http://localhost:7444")' | python3
        interval: 30s
        timeout: 30s
        retries: 3

  memgraphlab:
    image: memgraph/lab:2.15.0
    container_name: memgraph-lab
    ports:
      - "3000:3000"
    depends_on:
      - memgraphmage
    environment:
      - QUICK_CONNECT_MG_HOST=memgraphmage
      - QUICK_CONNECT_MG_PORT=7687
    networks:
      - esnet
    healthcheck:
        test: wget -O - http://localhost:3000 > /dev/null
        interval: 30s
        timeout: 30s
        retries: 3

networks:
  esnet: