version: '3'
services:

  # sidecar container to run commands for setting up elasticsearch
  elasticsearch-setup:
    build: ./elasticsearch-setup
    container_name: elasticsearch-setup
    networks:
      - esnet
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: elasticsearch:7.12.0
    container_name: elasticsearch
    environment:
      - network.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - node.name=cluster1-node1
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - esnet
    healthcheck:
        test: "curl --silent --fail --user elastic:changeme localhost:9200/_cluster/health || exit 1"
        interval: 10s
        timeout: 30s
        retries: 3

  kibana:
    image: kibana:7.12.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=changeme
    # some things are just too complicated to specify as env vars... so into a yml they go
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - esnet
    depends_on:
      - elasticsearch
    healthcheck:
        test: "curl --silent --fail localhost:5601 || exit 1"
        interval: 30s
        timeout: 30s
        retries: 3

  apm-server:
    image: elastic/apm-server:7.12.0
    container_name: apm-server
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    ports:
      - 8200:8200
    command: >
       apm-server -e
         -E apm-server.host="0.0.0.0:8200"
         -E output.elasticsearch.hosts=["http://elasticsearch:9200"]
         -E output.elasticsearch.username=elastic
         -E output.elasticsearch.password=changeme
         -E logging.level=debug
         -E apm-server.default_service_environment=development
    networks:
      - esnet
    depends_on:
      - elasticsearch
      - kibana

  metricbeat:
    image: elastic/metricbeat:7.12.0
    container_name: metricbeat
    volumes:
      - /var:/varfs:ro
      - /home:/homefs:ro
    command: >
       metricbeat -e
         -E output.elasticsearch.hosts=["http://elasticsearch:9200"]
         -E output.elasticsearch.username=elastic
         -E output.elasticsearch.password=changeme
         -E logging.level=info
         -E name=aloha
    networks:
      - esnet
    depends_on:
      - elasticsearch
      - kibana

networks:
  esnet: